# Generated by Django 4.0.6 on 2022-08-04 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_couponcode_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='coupon',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_0-9]*$', 'Only uppercase letters and numbers and underscores allowed.')]),
        ),
    ]
