# Generated by Django 4.0.6 on 2022-08-04 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_couponcode_qty_alter_couponcode_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='qty',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
